### PR TITLE
Set native downloader as default

### PR DESCRIPTION
**Pull request by jedevc**
This PR sets the native downloader as the default for everything, while still leaving the selenium backends as optional.

This should make it easier to get other people to use this tool :)

### CODE REVIEW

**Comment by jedevc** [comment]
@Chasbob would love you to look over this before merging.

**Comment by Chasbob** [comment]
Will take a look later today. Would love to get the selenium

**Comment by Chasbob** [comment]
*Dependencies out of it to bring the total size down

I miss clicked send and don't see how to edit on the new android app🎉

**Comment by jedevc** [comment]
Maybe we can get a docker command to run it all now :D

**Review by Chasbob — APPROVED** [review]

**Comment by Chasbob** [comment]
Maybe look at merging #10 into this first

**Pull request merged**
